// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5896c741-e467-4381-b241-3f43c768b98b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DYQesdYZ4",
    "aws_user_pools_web_client_id": "547tivikaqko9rtr2u26h3jpiv",
    "oauth": {}
};


export default awsmobile;
